export default [
  "I'm baby farm-to-table offal pinterest marfa hella chambray. Kombucha ramps pok pok kinfolk knausgaard enamel pin. Normcore slow-carb godard brunch subway tile gochujang deep v, four loko glossier af man braid. Actually glossier sriracha gochujang.",

  "Swag forage beard vexillologist, kombucha VHS brunch gastropub scenester thundercats celiac. Leggings yuccie coloring book stumptown messenger bag kinfolk. You probably haven't heard of them glossier biodiesel prism offal. You probably haven't heard of them scenester authentic umami. Hell of swag artisan skateboard stumptown knausgaard cred try-hard irony kitsch gochujang man braid YOLO. Vaporware shabby chic blue bottle tilde. Helvetica keffiyeh portland, fashion axe kale chips drinking vinegar craft beer trust fund hashtag freegan live-edge salvia copper mug microdosing.",

  "Fanny pack gastropub tumblr fam deep v la croix green juice listicle hashtag tattooed blog austin. Ethical everyday carry la croix, gluten-free helvetica woke kickstarter banjo fanny pack hammock lumbersexual waistcoat williamsburg 90's. Vice shabby chic jean shorts pour-over offal 90's sustainable fixie iPhone man braid umami VHS authentic. Sriracha edison bulb marfa bitters taxidermy organic. Succulents kale chips thundercats food truck butcher blog crucifix man braid shoreditch brunch. Tbh tousled kickstarter, 8-bit sustainable selfies asymmetrical master cleanse vegan succulents pork belly poke biodiesel. Authentic ugh chillwave chartreuse skateboard, seitan farm-to-table helvetica semiotics kickstarter heirloom activated charcoal.",

  'Intelligentsia la croix literally, VHS waistcoat twee ennui raw denim snackwave actually. +1 portland try-hard normcore. Shaman narwhal deep v mixtape. Twee pitchfork chillwave, deep v DIY tacos banh mi adaptogen authentic narwhal mixtape sriracha vexillologist selfies cliche. Kinfolk meditation squid banh mi. Polaroid gentrify yuccie dreamcatcher mlkshk, heirloom single-origin coffee shabby chic.',

  "Meditation freegan kinfolk, sustainable sriracha synth unicorn you probably haven't heard of them truffaut. Poutine pork belly organic, vaporware 90's poke mlkshk selfies live-edge tacos shabby chic brooklyn tousled franzen gluten-free. Cold-pressed scenester swag hell of. Cardigan meh bicycle rights, vape messenger bag yuccie chillwave. Wayfarers blue bottle vaporware try-hard swag freegan kickstarter migas semiotics stumptown fixie.",

  "Hammock wayfarers mustache distillery trust fund +1 godard man braid drinking vinegar banjo occupy. Fam seitan pinterest XOXO beard. Single-origin coffee palo santo four dollar toast af. Swag taiyaki polaroid you probably haven't heard of them intelligentsia normcore hashtag. Humblebrag aesthetic lyft blog.",

  "Offal la croix mixtape vice hot chicken wolf master cleanse four dollar toast unicorn cold-pressed williamsburg. Beard vegan hell of, hashtag polaroid shoreditch sartorial irony chambray. Swag migas heirloom chambray meditation, freegan fashion axe iPhone hammock snackwave air plant. Photo booth you probably haven't heard of them four loko narwhal, meh jean shorts ramps man bun skateboard iPhone selvage cred chicharrones semiotics bitters. Listicle sartorial artisan williamsburg yuccie palo santo, semiotics authentic thundercats hashtag actually letterpress chartreuse kickstarter.",

  'Hella cronut gochujang, ugh tilde pitchfork cardigan brooklyn farm-to-table lumbersexual master cleanse taiyaki bicycle rights. Retro thundercats gluten-free ethical schlitz +1 scenester kinfolk chambray cornhole. Chambray aesthetic pickled 3 wolf moon pour-over hashtag kombucha PBR&B VHS tofu. Migas etsy meditation tote bag thundercats fashion axe, before they sold out woke XOXO hexagon single-origin coffee. Craft beer kombucha sustainable bitters waistcoat pinterest. Umami la croix seitan mixtape raclette master cleanse. Freegan glossier farm-to-table artisan.',

  "Pour-over DIY authentic venmo. You probably haven't heard of them semiotics gluten-free, bitters paleo kale chips ethical pop-up typewriter try-hard. Mlkshk hashtag edison bulb portland hella tousled scenester, hell of bitters. Fingerstache health goth godard you probably haven't heard of them vice lumbersexual organic hella jianbing vexillologist raw denim 8-bit craft beer unicorn. Vape aesthetic master cleanse four loko, next level green juice quinoa hell of. Sartorial marfa cronut, semiotics la croix pickled gastropub.",

  "Lomo umami kombucha post-ironic vape, af enamel pin plaid. Jianbing kogi fanny pack portland venmo aesthetic thundercats semiotics tattooed health goth cold-pressed slow-carb sriracha authentic 90's. Twee live-edge schlitz squid man bun narwhal helvetica. Austin ennui man braid PBR&B kombucha vaporware tofu.",
];
